version: '3.7'
services:
  the-fe:
    build:
      context: .
    ports:
      - '8081:8080'
    restart: always
    container_name: the-fe
    networks:
      - the_net


networks:
  the_net:
    driver: bridge
